- name: packer-oracle-soa assistant
  hosts: 127.0.0.1

  vars_prompt:
    - name: "providers"
      prompt: "providers? (virtualbox,docker,aws)"
      default:
      private: no
    - name: "debug"
      prompt: "debug? (true or false)"
      default: no
      private: no
    - name: "os"
      prompt: "os? (ol7 or centos7)"
      default: "centos7"
      private: no
    - name: "release"
      prompt: "release? (12.1.3 or 12.2.1)"
      default: "12.1.3"
      private: no
    - name: "quick"
      prompt: "quick installer? (true or false)"
      default: "true"
      private: no
    - name: "bpm"
      prompt: "install bpm? (true or false)"
      default: "false"
      private: no
    - name: "download"
      prompt: "download artifacts? (true or false)"
      default: "true"
      private: no
  tasks:
    - set_fact:
        only_providers: -only={{ providers }}
      when: providers is defined and providers != ""

    - set_fact:
        debug_text: "-debug=true"
      when: debug | bool

    - set_fact:
        debug_text: "-debug=false"
      when: not debug | bool

    - set_fact:
        variables: oracle-soa-qs-12.1.3-{{ os }}.json
        installers:
          - "{{ ansible_env.HOME }}/oracle/fmw/installers/12.1.3/fmw_12.1.3.0.0_soaqs_Disk1_1of1.zip"
      when: quick | bool and not bpm | bool and release == "12.1.3"

    - set_fact:
        variables: oracle-bpm-qs-12.1.3-{{ os }}.json
        installers:
          - "{{ ansible_env.HOME }}/oracle/fmw/installers/12.1.3/fmw_12.1.3.0.0_bpmqs_Disk1_1of1.zip"
      when: quick | bool and bpm | bool and release == "12.1.3"

    - set_fact:
        variables: oracle-soa-qs-12.2.1-{{ os }}.json
        installers:
          - "{{ ansible_env.HOME }}/oracle/fmw/installers/12.2.1/fmw_12.2.1.0.0_soaqs_Disk1_1of2.zip"
          - "{{ ansible_env.HOME }}/oracle/fmw/installers/12.2.1/fmw_12.2.1.0.0_soaqs_Disk1_2of2.zip"
      when: quick | bool and not bpm | bool and release == "12.2.1"

    - set_fact:
        variables: oracle-bpm-qs-12.2.1-{{ os }}.json
        installers:
          - "{{ ansible_env.HOME }}/oracle/fmw/installers/12.2.1/fmw_12.2.1.0.0_bpmqs_Disk1_1of2.zip"
          - "{{ ansible_env.HOME }}/oracle/fmw/installers/12.2.1/fmw_12.2.1.0.0_bpmqs_Disk1_2of2.zip"
      when: quick | bool and bpm | bool and release == "12.2.1"

    - debug:
        msg: "{{ variables }} template will be built"

    - shell: "ansible-galaxy install -f -p ./roles -r roles.yml"
      when: download | bool

    - copy:
        src: "{{ item }}"
        dest: roles/oracle-soa/files/
        force: no
      with_items: "{{ installers }}"
      when: download | bool

    - shell: "packer build -var-file={{ variables }} -force=true {{ debug_text }} {{ only_providers }} oracle-soa.json >> build.log"
